#!/usr/bin/env node
/**
 * Interactive merge-writer for .env.local + .dev.vars (readline).
 *
 * .env.local feeds Vite (VITE_* + a few server-side mirrors).
 * .dev.vars feeds wrangler dev (server secrets read by the Worker bindings).
 *
 * Run: npm run env:wizard
 */
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const envPath = path.join(root, ".env.local");

/** @type {{ key: string; hint?: string }[]} */
const WIZARD_KEYS = [
  // Auth (also need to be mirrored to .dev.vars for the Worker)
  { key: "AUTH_GOOGLE_ID", hint: "Google OAuth client ID" },
  { key: "AUTH_GOOGLE_SECRET", hint: "Google OAuth client secret" },
  { key: "AUTH_SECRET", hint: "Auth.js secret (openssl rand -base64 32)" },
  { key: "AUTH_TRUST_HOST", hint: "Usually true on Cloudflare Workers" },
  // S3-compatible R2 credentials for presigned uploads
  { key: "S3_ENDPOINT", hint: "R2 S3 API endpoint (account host)" },
  { key: "S3_REGION", hint: "auto" },
  { key: "S3_BUCKET", hint: "R2 bucket name (pdftrusted)" },
  { key: "S3_ACCESS_KEY_ID", hint: "R2 access key (Manage R2 API Tokens)" },
  { key: "S3_SECRET_ACCESS_KEY", hint: "R2 secret key" },
  // PayPal (sole payment provider)
  { key: "PAYPAL_CLIENT_ID", hint: "PayPal REST app client ID" },
  { key: "PAYPAL_CLIENT_SECRET", hint: "PayPal REST app secret" },
  { key: "PAYPAL_WEBHOOK_ID", hint: "PayPal webhook ID from dashboard" },
  { key: "PAYPAL_PLAN_PREMIUM_MONTHLY", hint: "PayPal subscription plan ID (monthly)" },
  { key: "PAYPAL_PLAN_PREMIUM_YEARLY", hint: "PayPal subscription plan ID (yearly)" },
  { key: "PAYPAL_MODE", hint: "sandbox or live" },
  { key: "NEXT_PUBLIC_PAYMENTS_ENABLED", hint: "true when PayPal checkout is live" },
  // Dev routing
  { key: "VITE_API_PROXY_TARGET", hint: "Dev: proxy /api to this origin (default http://localhost:8787)" },
  { key: "VITE_MOCK_PREMIUM", hint: "Dev: true to mock premium" },
  // SEO / observability
  { key: "VITE_GOOGLE_SITE_VERIFICATION", hint: "Search Console HTML tag content" },
  { key: "VITE_GA_MEASUREMENT_ID", hint: "GA4 measurement ID" },
  { key: "VITE_SENTRY_DSN", hint: "Sentry DSN (optional)" },
  // App config
  { key: "VITE_ADSENSE_CLIENT_ID", hint: "AdSense publisher ID" },
  { key: "VITE_APP_URL", hint: "Public site URL (https://www.pdftrusted.com)" },
];

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * @param {string[]} lines
 * @param {string} key
 * @param {string} value
 * @returns {string[]}
 */
function upsertLine(lines, key, value) {
  const re = new RegExp(`^${escapeRe(key)}=`);
  const next = lines.slice();
  let i = next.findIndex((l) => re.test(l.trimStart()));
  const line = `${key}=${value}`;
  if (i >= 0) next[i] = line;
  else next.push(line);
  return next;
}

/**
 * @param {string} text
 * @returns {string[]}
 */
function toLines(text) {
  if (!text) return [];
  return text.replace(/\r\n/g, "\n").split("\n");
}

async function main() {
  const rl = createInterface({ input, output });
  let raw = "";
  try {
    raw = await fs.readFile(envPath, "utf8");
  } catch {
    raw = "";
  }
  let lines = toLines(raw);
  if (lines.length === 0) {
    lines = ["# PDFTrusted — generated by env:wizard", ""];
  }

  let saved = 0;
  let skipped = 0;
  let kept = 0;

  output.write("\n=== PDFTrusted .env.local wizard ===\n");
  output.write(`File: ${envPath}\n`);
  output.write("Per key: Enter=new value | Enter empty=keep | s=skip this key\n\n");

  for (const { key, hint } of WIZARD_KEYS) {
    const re = new RegExp(`^${escapeRe(key)}=(.*)$`);
    const existing = lines.find((l) => re.test(l.trimStart()));
    const current = existing ? existing.replace(/^[^=]+=/, "").trim() : "";
    const display = current ? (key.includes("SECRET") || key.includes("KEY") || key.includes("PASSWORD") ? "(set, hidden)" : current) : "(empty)";
    output.write(`\n--- ${key}${hint ? ` — ${hint}` : ""} ---\n`);
    output.write(`Current: ${display}\n`);
    const ans = (await rl.question("Value [keep/skip]: ")).trim();
    if (ans.toLowerCase() === "s" || ans.toLowerCase() === "[s]" || ans.toLowerCase() === "skip") {
      skipped += 1;
      continue;
    }
    if (ans === "") {
      kept += 1;
      continue;
    }
    lines = upsertLine(lines, key, ans);
    await fs.writeFile(envPath, lines.join("\n"), "utf8");
    saved += 1;
    console.log(`Saved ${key} to .env.local`);
  }

  await rl.close();
  output.write(`\nDone. Saved: ${saved}, Kept: ${kept}, Skipped: ${skipped}\n`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
