export type LangOption = { code: string; label: string };

/** 100+ languages for AI translate & summarize output. */
export const TRANSLATE_LANG_OPTIONS: LangOption[] = [
  { code: "en", label: "English" },
  { code: "hi", label: "Hindi" },
  { code: "es", label: "Spanish" },
  { code: "fr", label: "French" },
  { code: "de", label: "German" },
  { code: "it", label: "Italian" },
  { code: "pt", label: "Portuguese" },
  { code: "ru", label: "Russian" },
  { code: "zh", label: "Chinese (Simplified)" },
  { code: "zh-TW", label: "Chinese (Traditional)" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "ar", label: "Arabic" },
  { code: "bn", label: "Bengali" },
  { code: "ur", label: "Urdu" },
  { code: "pa", label: "Punjabi" },
  { code: "ta", label: "Tamil" },
  { code: "te", label: "Telugu" },
  { code: "mr", label: "Marathi" },
  { code: "gu", label: "Gujarati" },
  { code: "kn", label: "Kannada" },
  { code: "ml", label: "Malayalam" },
  { code: "ne", label: "Nepali" },
  { code: "si", label: "Sinhala" },
  { code: "th", label: "Thai" },
  { code: "vi", label: "Vietnamese" },
  { code: "id", label: "Indonesian" },
  { code: "ms", label: "Malay" },
  { code: "tl", label: "Filipino" },
  { code: "tr", label: "Turkish" },
  { code: "fa", label: "Persian" },
  { code: "he", label: "Hebrew" },
  { code: "pl", label: "Polish" },
  { code: "uk", label: "Ukrainian" },
  { code: "cs", label: "Czech" },
  { code: "sk", label: "Slovak" },
  { code: "hu", label: "Hungarian" },
  { code: "ro", label: "Romanian" },
  { code: "bg", label: "Bulgarian" },
  { code: "hr", label: "Croatian" },
  { code: "sr", label: "Serbian" },
  { code: "sl", label: "Slovenian" },
  { code: "el", label: "Greek" },
  { code: "nl", label: "Dutch" },
  { code: "sv", label: "Swedish" },
  { code: "no", label: "Norwegian" },
  { code: "da", label: "Danish" },
  { code: "fi", label: "Finnish" },
  { code: "et", label: "Estonian" },
  { code: "lv", label: "Latvian" },
  { code: "lt", label: "Lithuanian" },
  { code: "is", label: "Icelandic" },
  { code: "ga", label: "Irish" },
  { code: "cy", label: "Welsh" },
  { code: "ca", label: "Catalan" },
  { code: "eu", label: "Basque" },
  { code: "gl", label: "Galician" },
  { code: "af", label: "Afrikaans" },
  { code: "sw", label: "Swahili" },
  { code: "am", label: "Amharic" },
  { code: "ha", label: "Hausa" },
  { code: "yo", label: "Yoruba" },
  { code: "ig", label: "Igbo" },
  { code: "zu", label: "Zulu" },
  { code: "xh", label: "Xhosa" },
  { code: "so", label: "Somali" },
  { code: "rw", label: "Kinyarwanda" },
  { code: "mg", label: "Malagasy" },
  { code: "km", label: "Khmer" },
  { code: "lo", label: "Lao" },
  { code: "my", label: "Burmese" },
  { code: "ka", label: "Georgian" },
  { code: "hy", label: "Armenian" },
  { code: "az", label: "Azerbaijani" },
  { code: "kk", label: "Kazakh" },
  { code: "uz", label: "Uzbek" },
  { code: "ky", label: "Kyrgyz" },
  { code: "tg", label: "Tajik" },
  { code: "mn", label: "Mongolian" },
  { code: "ps", label: "Pashto" },
  { code: "ku", label: "Kurdish" },
  { code: "sd", label: "Sindhi" },
  { code: "as", label: "Assamese" },
  { code: "or", label: "Odia" },
  { code: "mai", label: "Maithili" },
  { code: "sa", label: "Sanskrit" },
  { code: "la", label: "Latin" },
  { code: "sq", label: "Albanian" },
  { code: "mk", label: "Macedonian" },
  { code: "bs", label: "Bosnian" },
  { code: "mt", label: "Maltese" },
  { code: "lb", label: "Luxembourgish" },
  { code: "be", label: "Belarusian" },
  { code: "eo", label: "Esperanto" },
  { code: "jv", label: "Javanese" },
  { code: "su", label: "Sundanese" },
  { code: "ceb", label: "Cebuano" },
  { code: "haw", label: "Hawaiian" },
  { code: "mi", label: "Maori" },
  { code: "sm", label: "Samoan" },
  { code: "ht", label: "Haitian Creole" },
  { code: "qu", label: "Quechua" },
  { code: "gn", label: "Guarani" },
  { code: "ay", label: "Aymara" },
  { code: "tk", label: "Turkmen" },
  { code: "tt", label: "Tatar" },
  { code: "ug", label: "Uyghur" },
  { code: "bo", label: "Tibetan" },
  { code: "dz", label: "Dzongkha" },
  { code: "lb-LU", label: "Luxembourgish (alt)" },
];

const LABEL_BY_CODE = new Map(TRANSLATE_LANG_OPTIONS.map((l) => [l.code, l.label]));

export function langLabel(code: string): string {
  return LABEL_BY_CODE.get(code) ?? code.replace(/-/g, " ");
}
